name: my-check

on: push
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: set up Python
              uses: actions/setup-python@v5
            - name: install dependencies 
              run: |
                pip install uv
                make install
            - name: run lint and tests
              run: |
                make lint
                make test
                make coverage
            - name: SonarQubeScan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: >
                    -Dsonar.projectKey=hexlet-boilerplates_python-package
                    -Dsonar.organization=hexlet-boilerplates
                    -Dsonar.python.coverage.reportPaths=coverage.xml