name: my-check

on: push
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: set up Python
              uses: actions/setup-python@v5
            - name: install dependencies 
              run: |
                pip install uv
                make install
            - name: run lint and tests
              run: |
                make lint
                make test
                make coverage
            - name: Install tox and any other packages
              run: pip install tox
            - name: Run tox
              run: tox -e py
            - name: SonarQubeScan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
